# Alacritty Configuration (TOML)

[window]
opacity = 0.9
decorations = "full"
dynamic_padding = true
dynamic_title = true

[font.normal]
family = "monospace"

[font]
size = 9.0

# Optional font offset and glyph_offset (commented for now)
[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

# colors section
[colors.primary]
background = "#000000"
foreground = "#aaaaaa"

[colors.selection]
text = "#000000"
background = "#b4d5ff"

[colors.cursor]
text = "#111111"
cursor = "#aaaaaa"

[colors.normal]
black = "#1e1e1e"
red = "#c01c28"
green = "#26a269"
yellow = "#a2734c"
blue = "#12488b"
magenta = "#a347ba"
cyan = "#2aa1b3"
white = "#cfcfcf"

[colors.bright]
black = "#5d5d5d"
red = "#f66151"
green = "#33d17a"
yellow = "#e9ad0c"
blue = "#2a7bde"
magenta = "#c061cb"
cyan = "#33c7de"
white = "#ffffff"

[cursor.style]
shape = "Beam"
blinking = "On"

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

# Logging settings
# [debug]
# render_timer = false
# persistent_logging = false
# log_level = "Warn"
